copyright: Copyright &copy; 2023 THOORENS Bruno - MIT licence
docs_dir: docs
markdown_extensions:
- smarty
- def_list
- pymdownx.tasklist:
    custom_checkbox: false
nav:
- Home: index.md
- Widgets: widget.md
- Model: model.md
- Basic input/output: bio.md
plugins:
- search
repo_name: GitHub
repo_url: https://github.com/Moustikitos/tkinter-map
site_name: The tkinter map canvas
theme:
  name: readthedocs
  nav_style: light
